### ISSUE TITLE
Usable eprintf for csh

### ISSUE THREAD

**Issue by freebsdfrau** [FrauBSD/secure_thumb#2]
https://github.com/FrauBSD/secure_thumb/blob/cd2f39d536ac1bdc257b2f766b22cc1c29d1437f/etc/ssh.csh#L62

Even if we can not send data to stderr from [t]csh natively, we should probably just make it function like printf:

```
quietly unalias eprintf
alias eprintf printf
```

**Comment by kfv** [comment]
Neat, brilliant. Roger that, I'll take care of it, thanks for the tip.
